### PR TITLE
Split tests into seperate jobs to run in parallel

### PR DESCRIPTION
**Pull request by JLockerman**
Speeding up CI

### CODE REVIEW

**Comment by JLockerman** [comment]
Looking at [our actions](https://github.com/timescale/promscale/actions) it seems like this change reduces the test time from around 10m to around 5m

**Comment by JLockerman** [comment]
if we switch to testing each module individually instead of using `go test ./...` we can parallelize even more

**Comment by antekresic** [comment]
Could we use some caching to reduce the go module downloading? 

https://github.com/actions/cache/blob/main/examples.md#go---modules

**Comment by JLockerman** [comment]
@antekresic almost certainly, though since a build on.y takes ~30s I'm not sure how much it'll help

**Review by antekresic — APPROVED** [review]
I think this looks good to merge, once you get rid of the unused function.

**Comment by antekresic** [comment]
@cevian what do you think about this one? I like it, anything that can speed CI is a good change in my book.

**Comment by JLockerman** [comment]
One issue is that I'm not sure how much it's actually speeding things up at

**Comment by JLockerman** [comment]
(whoops, wrong button)

**Comment by JLockerman** [comment]
Currently two outstanding issues:
1. it's using the wrong docker image for most of the tests
2. I'm not sure if it's actually speeding up CI

**Comment by antekresic** [comment]
Superseded by #395

**Pull request closed without merging**
