### PR TITLE
Helm CI tests

### PR DESCRIPTION
**Pull request by paulfantom**
This is a follow-up to work started in https://github.com/timescale/promscale/pull/947

To properly enable `ct` we need to move chart into a subdirectory. This is necessary to allow `ct` proper detection of `Chart.yaml` file.

List of chages:
- chart moved to `deploy/helm-chart`
- added CI workflow for helm chart testing
- added necessary fields of `home` and `appVersion` to `Chart.yaml` file

Tested locally with:
- ct 3.4.0
- yamllint 1.26.0
- yamle latest

Test command and output:
```console
$ ct --config ct.yaml lint --debug
Linting charts...
>>> helm version --short
>>> git rev-parse --is-inside-work-tree
>>> git merge-base origin/master HEAD
>>> git diff --find-renames --name-only 5d7e762e34f2de1f30d3cc4e2b04a4d97f1372ec -- deploy
Directory 'deploy/static' is not a valid chart directory. Skipping...

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 promscale => (version: "0.7.1", path: "deploy/helm-chart")
------------------------------------------------------------------------------------------------------------------------

>>> helm dependency build deploy/helm-chart
Linting chart 'promscale => (version: "0.7.1", path: "deploy/helm-chart")'
Checking chart 'promscale => (version: "0.7.1", path: "deploy/helm-chart")' for a version bump...
>>> git cat-file -e origin/master:deploy/helm-chart/Chart.yaml
Unable to find chart on master. New chart detected.
>>> yamale --schema /home/paulfantom/.ct/chart_schema.yaml deploy/helm-chart/Chart.yaml
Validating /home/paulfantom/Projects/src/github.com/timescale/promscale/deploy/helm-chart/Chart.yaml...
Validation success! 👍
>>> yamllint --config-file /home/paulfantom/.ct/lintconf.yaml deploy/helm-chart/Chart.yaml
>>> yamllint --config-file /home/paulfantom/.ct/lintconf.yaml deploy/helm-chart/values.yaml
>>> helm lint deploy/helm-chart
==> Linting deploy/helm-chart
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ promscale => (version: "0.7.1", path: "deploy/helm-chart")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

### CODE REVIEW

**Review by JamesGuthrie — APPROVED** [review]
LGTM

**Comment by cevian** [comment]
would moving this into /charts/promscale or  /charts/connector be better than /deploy/helm-charts. Seems more standard that way? but I'm not sure what your thinking was.

**Comment by paulfantom** [comment]
I would be in favor of moving into `charts` if we had more than one helm chart. However since currently we only have one, I tend to prefer having all deployment mechanisms in one top-level directory for easier management and discoverability. But I am not tied to this and having this in `charts/` works for me too.

@cevian which way would you like to go?

**Comment by cevian** [comment]
ahh  `I tend to prefer having all deployment mechanisms in one top-level directory for easier management and discoverability` 

makes sense to me.

**Review by cevian — APPROVED** [review]

**Comment by paulfantom** [comment]
Rebased to fix merge conflicts

**Pull request merged**
