### PR TITLE
Update PromQL till Sept 30, 2022

### PR DESCRIPTION
**Pull request by Harkishen-Singh**
Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

This commit updates the existing pkg/promql from upstream. It adds all the commits in [prometheus/promql module](https://github.com/prometheus/prometheus/commits/main/promql) upto and including September 30, with a1d6ba59acbfcabee7575cc43c71e9a02891ec30 being the final commit.

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

### CODE REVIEW

**Review by arajkumar — COMMENTED** [review]
Can you update to the latest prometheus release commit?

**Comment by feld** [comment]
I'm in the process of updating Promscale in the FreeBSD packages/ports and a version that supports at least Go 1.18 is required as FreeBSD doesn't support/ship Go 1.17 anymore. Looking forward to this next release. ✌️

**Comment by alejandrodnm** [comment]
> I'm in the process of updating Promscale in the FreeBSD packages/ports and a version that supports at least Go 1.18 is required as FreeBSD doesn't support/ship Go 1.17 anymore. Looking forward to this next release. ✌️

@feld we have been using golang 1.18 since March [ for some time now ](https://github.com/timescale/promscale/commit/78363830f5a419c1fda353c59c8c03941d5d8ab7)

**Review by cevian — APPROVED** [review]

**Comment by alejandrodnm** [comment]
@Harkishen-Singh should we fix and merge this?

**Comment by arajkumar** [comment]
@Harkishen-Singh Is it either pulled from [latest](https://github.com/prometheus/prometheus/tree/v2.41.0) or [latest - 1 ](https://github.com/prometheus/prometheus/tree/v2.40.7)release branch? Or do we have any policy on which branch to use?

**Comment by Harkishen-Singh** [comment]
@arajkumar the latest commits were fetched from main branch.

**Comment by arajkumar** [comment]
@Harkishen-Singh The problem with the main branch is that it may not be stable. It is always better to pull from stable branch and stable-1 for ultra safe :)

**Comment by Harkishen-Singh** [comment]
@arajkumar with [Revert code to match with v2.30.2 Prometheus release.](https://github.com/timescale/promscale/pull/1713/commits/b132c365357a4d467bb6def22c9ba6881e64faf7) the PR will now reflect the changes in the latest stable branch of v2.39, which is [`2.39.2`](https://github.com/prometheus/prometheus/commits/v2.39.2/promql). This was the last stable version before sparse-histgram release.

**Review by alejandrodnm — APPROVED** [review]

**Review by arajkumar — APPROVED** [review]

**Pull request merged**
