### PR TITLE
Move tests to top of pkg

### PR DESCRIPTION
**Pull request by blagojts**
Current tree:
```
.
├── pgmodel
├── pgxconn
├── prompb
├── tests
│   ├── end_to_end_tests
│   │   ├── concurrent_sql_test.go
│   │   ├── create_test.go
│   │   ├── datasets_test.go
│   │   ├── delete_test.go
│   │   ├── drop_test.go
│   │   ├── functions_test.go
│   │   ├── golden_files_test.go
│   │   ├── main_test.go
│   │   ├── migrate_test.go
│   │   ├── nan_test.go
│   │   ├── promql_endpoint_integration_test.go
│   │   ├── promql_label_endpoint_test.go
│   │   ├── promql_query_endpoint_test.go
│   │   ├── promql_series_endpoint_test.go
│   │   ├── promql_write_endpoint_test.go
│   │   ├── query_integration_test.go
│   │   ├── sql_bench_test.go
│   │   └── view_test.go
│   ├── testdata
│   │   ├── expected
│   │   │   ├── info_view-postgres.out
│   │   │   ├── info_view-timescaledb-2-multinode.out
│   │   │   ├── info_view-timescaledb-2.out
│   │   │   ├── info_view-timescaledb.out
│   │   │   ├── views-2.out
│   │   │   ├── views.out
│   │   │   └── views-timescaledb-2-multinode.out
│   │   ├── import.json
│   │   ├── real-dataset.sz
│   │   └── sql
│   │       ├── info_view.sql
│   │       └── views.sql
│   ├── test_migrations
│   │   ├── generate.go
│   │   ├── migration_files_generated.go
│   │   ├── migrations.go
│   │   └── sql
│   │       ├── idempotent
│   │       │   ├── 1-toc-run_second.sql
│   │       │   └── 2-toc-run_first.sql
│   │       ├── preinstall
│   │       │   └── 001-setup.sql
│   │       └── versions
│   │           └── dev
│   │               ├── 0.10.0-dev
│   │               │   ├── 1-migr_98_at.sql
│   │               │   └── 2-1_mig.sql
│   │               ├── 0.10.1-dev
│   │               │   ├── 1-migr_98_at.sql
│   │               │   └── 2-1_mig.sql
│   │               ├── 0.10.2-beta.dev
│   │               │   └── 1-migr_98_at.sql
│   │               ├── 0.1.0-dev
│   │               │   └── 1-migration.sql
│   │               ├── 0.2.0-dev
│   │               │   └── 1-migration.sql
│   │               └── 0.9.0-dev
│   │                   └── 1-migration.sql
│   └── upgrade_tests
│       └── upgrade_test.go
├── util
└── version
```
Old tree (master):
```
.
├── api
├── clockcache
├── internal
├── log
├── pgclient
├── pgmodel
│   ├── end_to_end_tests
│   │   ├── concurrent_sql_test.go
│   │   ├── create_test.go
│   │   ├── datasets_test.go
│   │   ├── delete_test.go
│   │   ├── drop_test.go
│   │   ├── functions_test.go
│   │   ├── golden_files_test.go
│   │   ├── main_test.go
│   │   ├── migrate_test.go
│   │   ├── nan_test.go
│   │   ├── promql_endpoint_integration_test.go
│   │   ├── promql_label_endpoint_test.go
│   │   ├── promql_query_endpoint_test.go
│   │   ├── promql_series_endpoint_test.go
│   │   ├── promql_write_endpoint_test.go
│   │   ├── query_integration_test.go
│   │   ├── sql_bench_test.go
│   │   └── view_test.go
│   ├── migrations
│   ├── testdata
│   │   ├── expected
│   │   │   ├── info_view-postgres.out
│   │   │   ├── info_view-timescaledb-2-multinode.out
│   │   │   ├── info_view-timescaledb-2.out
│   │   │   ├── info_view-timescaledb.out
│   │   │   ├── views-2.out
│   │   │   ├── views.out
│   │   │   └── views-timescaledb-2-multinode.out
│   │   ├── import.json
│   │   ├── real-dataset.sz
│   │   └── sql
│   │       ├── info_view.sql
│   │       └── views.sql
│   ├── test_migrations
│   │   ├── generate.go
│   │   ├── migration_files_generated.go
│   │   ├── migrations.go
│   │   └── sql
│   │       ├── idempotent
│   │       │   ├── 1-toc-run_second.sql
│   │       │   └── 2-toc-run_first.sql
│   │       ├── preinstall
│   │       │   └── 001-setup.sql
│   │       └── versions
│   │           └── dev
│   │               ├── 0.10.0-dev
│   │               │   ├── 1-migr_98_at.sql
│   │               │   └── 2-1_mig.sql
│   │               ├── 0.10.1-dev
│   │               │   ├── 1-migr_98_at.sql
│   │               │   └── 2-1_mig.sql
│   │               ├── 0.10.2-beta.dev
│   │               │   └── 1-migr_98_at.sql
│   │               ├── 0.1.0-dev
│   │               │   └── 1-migration.sql
│   │               ├── 0.2.0-dev
│   │               │   └── 1-migration.sql
│   │               └── 0.9.0-dev
│   │                   └── 1-migration.sql
│   └── upgrade_tests
│       └── upgrade_test.go
├── pgxconn
├── prompb
├── promql
├── query
├── runner
├── util
└── version
```
Displaying only moved files and top level directories

### CODE REVIEW

**Comment by Harkishen-Singh** [comment]
Can you please post the output of `tree` from the root of the project? It will help make the review process easier.

**Comment by blagojts** [comment]
@Harkishen-Singh I edited the PR description with the tree-diff

**Comment by Harkishen-Singh** [comment]
Yeah, its more easier to understand now. thank you.

**Review by Harkishen-Singh — APPROVED** [review]
lgtm

**Review by cevian — APPROVED** [review]
Great!

**Pull request merged**
