### PR TITLE
Add note in cron jobs step in bare-metal install docs

### PR DESCRIPTION
**Pull request by VineethReddy02**
Today Promscale doesn't need an explicit cronjob to perform maintenance tasks. This is internally performed using User Defined Jobs.

### CODE REVIEW

**Comment by JamesGuthrie** [comment]
This fixes #910

**Comment by JamesGuthrie** [comment]
What about in the docker installation notes? https://github.com/timescale/promscale/blob/master/docs/docker.md

**Comment by VineethReddy02** [comment]
Good catch @JamesGuthrie :)

Btw I just found we have two files almost describing the same steps on the installation of bare-metal i.e. 
https://github.com/timescale/promscale/blob/master/docs/bare-metal-promscale-stack.md
https://github.com/timescale/promscale/blob/master/docs/binary.md

It's ti,e to drop one.

**Comment by JamesGuthrie** [comment]
Sorry, one more thing: while we're at it I suppose that we can also remove `docs/scripts/*`.

**Review by cevian — APPROVED** [review]

**Comment by cevian** [comment]
@VineethReddy02 the idea for https://github.com/timescale/promscale/blob/master/docs/bare-metal-promscale-stack.md was to do the entire stack (as opposed to just Promscale connector). Do you think that no-longer makes sense?

**Review by jgpruitt — APPROVED** [review]

**Review by JamesGuthrie — CHANGES_REQUESTED** [review]
Can we remove the `docs/scripts` directory?

**Comment by VineethReddy02** [comment]
@cevian makes sense for now to maintain two files on bare metal install of Promscale and the entire stack will re-iterate over this approach later. 

@JamesGuthrie I made changes inline to Ramon's changes in #996 to add a note rather than dropping it completely for now considering backward compatibility, for users that are still using TimescaleDB `1.X`.

**Review by cevian — APPROVED** [review]

**Review by JamesGuthrie — APPROVED** [review]

**Comment by cevian** [comment]
@VineethReddy02 should this be merged?

**Comment by VineethReddy02** [comment]
Yup! Merging this right away.

**Pull request merged**
