### PR TITLE
Add workflow call in e2e tests

### PR DESCRIPTION
**Pull request by cevian**
This should allow this workflow to be called from other repos.
Namely we should be able to call this from the promscale_extension.

The workflow dispatch was changed to operate through the workflow_call.

## Description

*Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.*

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

### CODE REVIEW

**Review by paulfantom — CHANGES_REQUESTED** [review]
This is getting overly complicated. Can we have a document in `docs/` describing how our CI works?

**Comment by sumerman** [comment]
> This is getting overly complicated. Can we have a document in `docs/` describing how our CI works?

We intend to document `promscale_extension` CI in its own repo. This PR doesn't change anything for the connector, it merely consolidates docker-image discovery and enables external calls.

**Comment by sumerman** [comment]
Perhaps, to simplify it, we could get rid of `workflow_dispatch` as it should become of little use after this change. @paulfantom  @cevian WDYT?

**Comment by paulfantom** [comment]
I am OK with the removal of `workflow_dispatch` to simplify things and documenting how CI works in a document in the extension repo. It would be nice to put a link to that document in a code comment to increase visibility.

**Comment by sumerman** [comment]
> Preferably I would see that document written (WIP PR would be a nice start :) ) before this PR is merged.

https://github.com/timescale/promscale_extension/blob/36e6e2c37c9dc669ab9c8098138d5d97167fa849/.github/README.md

**Review by paulfantom — APPROVED** [review]

**Pull request merged**
