### PR TITLE
Avoid sending telemetry in CI tests

### PR DESCRIPTION
**Pull request by Harkishen-Singh**
Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

### CODE REVIEW

**Review by cevian — CHANGES_REQUESTED** [review]
I think this whole PR can be a one-line change.
in postgres_container.go line 478 add "-c", "timescaledb.telemetry_level=off"

**Review by antekresic — CHANGES_REQUESTED** [review]
What Mat said.

**Comment by Harkishen-Singh** [comment]
Ah, so this PR creates a problem for telemetry tests. The telemetry tests are designed to write telemetry metadata if the database telemetry is on. If it is set to off, the tests should not write any telemetry information. This is the expected case.

Now, this works well, which is the problem here. Since this PR sets the telemetry level to off, we can no longer write telemetry to database for testing in E2E tests.

One solution is to use the environment var, but wont work for all cases. Any suggestions please.

**Comment by cevian** [comment]
Ugh. Can we override the `If it is set to off, the tests should not write any telemetry information` behavior for the tests?

**Comment by Harkishen-Singh** [comment]
Let's dig into this PR only if this is a problem in the current telemetry state.

@VineethReddy02 can you please update here if there exist garbage values in telemetry data at the moment?

**Comment by Harkishen-Singh** [comment]
Closing this for the time since we are not sure that we get this in CI at the moment. We can come back to this PR in the future.

**Pull request closed without merging**
