### PR TITLE
Update sql_schema.md

### PR DESCRIPTION
**Pull request by SiddiqueAhmad**
typo in query

### CODE REVIEW

**Review by cevian — APPROVED** [review]
Thanks!

**Comment by SiddiqueAhmad** [comment]
sorry i merged the master in patch-1 rather rebase, is it fine ?

**Comment by cevian** [comment]
It would be better to do `git fetch origin; git rebase -i origin/master; git push -f`. But we can also do it if you prefer.

**Comment by SiddiqueAhmad** [comment]
done

**Pull request merged**
