### PR TITLE
Fix poor performance in maintenance tasks

### LINKED ISSUE #663: Promscale maintenance tasks are taking so long to compress the data
Hello,

I would like to report the issue after upgrading to promscale v0.4.0 (Docker image from [https://hub.docker.com/r/timescale/promscale](url))
Before upgrading to v0.4.0, we have 2 `execute_maintenance_job` jobs constantly running. It usually compress chunks in specific timeframe like (60-90 minutes). Therefore the rate of uncompressed chunks were almost near to some number.
### The Problem 
However after upgrade, the maintenance job can not keep up with compression and number of uncompressed chunks are constantly growing. Also the job is now taking more than **48 hours**!
We upgrade to v0.4.1 and still the issue exists. 
Here is the query results from job table:
```
prometheus=# SELECT * FROM timescaledb_information.jobs;
-[ RECORD 1 ]-----+------------------------------
job_id            | 2678
application_name  | User-Defined Action [2678]
schedule_interval | 00:30:00
max_runtime       | 00:00:00
max_retries       | -1
retry_period      | 00:05:00
proc_schema       | _prom_catalog
proc_name         | execute_maintenance_job
owner             | postgres
scheduled         | t
config            | 
next_start        | -infinity
hypertable_schema | 
hypertable_name   | 
-[ RECORD 2 ]-----+------------------------------
job_id            | 2679
application_name  | User-Defined Action [2679]
schedule_interval | 00:30:00
max_runtime       | 00:00:00
max_retries       | -1
retry_period      | 00:05:00
proc_schema       | _prom_catalog
proc_name         | execute_maintenance_job
owner             | postgres
scheduled         | t
config            | 
next_start        | -infinity
hypertable_schema | 
hypertable_name   | 
```
```
prometheus=# SELECT * FROM timescaledb_information.job_stats;
-[ RECORD 1 ]----------+------------------------------
hypertable_schema      | 
hypertable_name        | 
job_id                 | 2679
last_run_started_at    | 2021-06-11 06:02:15.496375+00
last_successful_finish | 2021-06-11 05:32:15.493223+00
last_run_status        | 
job_status             | Running
last_run_duration      | 
next_start             | -infinity
total_runs             | 535
total_successes        | 522
total_failures         | 6
-[ RECORD 2 ]----------+------------------------------
hypertable_schema      | 
hypertable_name        | 
job_id                 | 2678
last_run_started_at    | 2021-06-11 06:22:58.830334+00
last_successful_finish | 2021-06-11 05:52:58.828372+00
last_run_status        | 
job_status             | Running
last_run_duration      | 
next_start             | -infinity
total_runs             | 534
total_successes        | 523
total_failures         | 4
-[ RECORD 3 ]----------+------------------------------
hypertable_schema      | 
hypertable_name        | 
job_id                 | 1
last_run_started_at    | 2021-06-13 21:56:21.182706+00
last_successful_finish | 2021-05-31 00:08:17.176526+00
last_run_status        | Failed
job_status             | Scheduled
last_run_duration      | 00:01:40.042706
next_start             | 2021-06-14 18:16:46.225412+00
total_runs             | 389
total_successes        | 156
total_failures         | 233
```
We are running on TimescaleDB v2.3.0-pg12
```
Name        | timescaledb
Version     | 2.3.0
Schema      | public
Description | Enables scalable inserts and complex queries for time-series data
```
Following image is showing the number of uncompressed chunks. As you can clearly see the number significantly jumped after updating to v0.4.0
Screenshot 2021-06-14 at 10 16 54
Also following image shows how long a job takes to finish. Again, as you can see a job taking longer and longer to finished.
Screenshot 2021-06-14 at 10 13 31

 * The rate of data that are feed to Promscale from Prometheus is same as it was before.

### PR DESCRIPTION
**Pull request by cevian**
The maintenance tasks were not performing well due to
issue timescale/timescaledb#3404. Namely, the qualifier
on series_id were not being pushed down correctly to
compressed chunks on the metric table. So for example,
the old plan for the delete_expired_series query was

```
Update on container_memory_failures_total  (cost=0.00..39538450.88 rows=1 width=210)
   ->  Nested Loop Semi Join  (cost=0.00..39538450.88 rows=1 width=210)
         Join Filter: (container_memory_failures_total.id = potentially_drop_series.series_id)
         ->  Nested Loop  (cost=0.00..50249.71 rows=1148685 width=168)
               ->  Seq Scan on ids_epoch  (cost=0.00..1.01 rows=1 width=14)
               ->  Seq Scan on container_memory_failures_total  (cost=0.00..38761.85 rows=1148685 width=154)
                     Filter: (delete_epoch IS NULL)
         ->  Materialize  (cost=0.00..39470970.90 rows=1 width=50)
               ->  Nested Loop Anti Join  (cost=0.00..39470970.89 rows=1 width=50)
                     Join Filter: (data_exists.series_id = potentially_drop_series.series_id)
                     ->  Subquery Scan on potentially_drop_series  (cost=0.00..0.07 rows=1 width=40)
                           ->  Limit  (cost=0.00..0.06 rows=1 width=12)
                                 ->  HashSetOp Except  (cost=0.00..0.06 rows=1 width=12)
                                       ->  Append  (cost=0.00..0.05 rows=2 width=12)
                                             ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..0.02 rows=1 width=12)
                                                   ->  HashAggregate  (cost=0.00..0.01 rows=1 width=0)
                                                         Group Key: series_id
                                                         ->  Result  (cost=0.00..0.00 rows=0 width=0)
                                                               One-Time Filter: false
                                             ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..0.02 rows=1 width=12)
                                                   ->  HashAggregate  (cost=0.00..0.01 rows=1 width=0)
                                                         Group Key: series_id
                                                         ->  Result  (cost=0.00..0.00 rows=0 width=0)
                                                               One-Time Filter: false
                     ->  Append  (cost=0.00..11565989.70 rows=2232398490 width=18)
                           ->  Seq Scan on container_memory_failures_total data_exists_1  (cost=0.00..0.00 rows=1 width=18)
                                 Filter: ("time" >= '2021-02-11 13:11:07.779863+00'::timestamp with time zone)
                           ->  Custom Scan (DecompressChunk) on _hyper_318_62_chunk data_exists_2  (cost=0.04..2660.36 rows=67068000 width=18)
                                 Filter: ("time" >= '2021-02-11 13:11:07.779863+00'::timestamp with time zone)
                                 ->  Seq Scan on compress_hyper_333_9206_chunk  (cost=0.00..2660.36 rows=67068 width=136)
                                       Filter: (_ts_meta_max_1 >= '2021-02-11 13:11:07.779863+00'::timestamp with time zone)
                           ->  Custom Scan (DecompressChunk) on _hyper_318_4497_chunk data_exists_3  (cost=0.04..2698.91 rows=67432000 width=18)
                                 Filter: ("time" >= '2021-02-11 13:11:07.779863+00'::timestamp with time zone)
                                 ->  Seq Scan on compress_hyper_333_14717_chunk  (cost=0.00..2698.91 rows=67432 width=136)
                                       Filter: (_ts_meta_max_1 >= '2021-02-11 13:11:07.779863+00'::timestamp with time zone)
....
```

Notice the lack of quals on the compressed chunks.

The new plan is:
```
Update on container_memory_failures_total  (cost=3.03..6.28 rows=1 width=228)
   ->  Nested Loop  (cost=3.03..6.28 rows=1 width=228)
         ->  Nested Loop  (cost=3.03..5.26 rows=1 width=214)
               ->  HashAggregate  (cost=2.60..2.61 rows=1 width=68)
                     Group Key: potentially_drop_series.series_id
                     ->  Nested Loop Left Join  (cost=2.51..2.60 rows=1 width=68)
                           Filter: (ex.indicator IS NULL)
                           ->  Subquery Scan on potentially_drop_series  (cost=0.00..0.07 rows=1 width=40)
                                 ->  Limit  (cost=0.00..0.06 rows=1 width=12)
                                       ->  HashSetOp Except  (cost=0.00..0.06 rows=1 width=12)
                                             ->  Append  (cost=0.00..0.05 rows=2 width=12)
                                                   ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..0.02 rows=1 width=12)
                                                         ->  HashAggregate  (cost=0.00..0.01 rows=1 width=0)
                                                               Group Key: series_id
                                                               ->  Result  (cost=0.00..0.00 rows=0 width=0)
                                                                     One-Time Filter: false
                                                   ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..0.02 rows=1 width=12)
                                                         ->  HashAggregate  (cost=0.00..0.01 rows=1 width=0)
                                                               Group Key: series_id
                                                               ->  Result  (cost=0.00..0.00 rows=0 width=0)
                                                                     One-Time Filter: false
                           ->  Subquery Scan on ex  (cost=2.51..2.52 rows=1 width=32)
                                 ->  Limit  (cost=2.51..2.51 rows=1 width=12)
                                       ->  Custom Scan (ChunkAppend) on container_memory_failures_total data_exists  (cost=2.51..2.51 rows=1000 width=12)
                                             Order: data_exists."time"
                                             ->  Custom Scan (DecompressChunk) on _hyper_318_62_chunk data_exists_1  (cost=2.51..2.51 rows=1000 width=8)
                                                   Filter: ("time" >= '2021-02-11 13:11:07.779863+00'::timestamp with time zone)
                                                   ->  Index Scan using compress_hyper_333_9206_chunk__compressed_hypertable_333_series on compress_hyper_333_9206_chunk  (cost=0.29..2.51 rows=1 width=56)
                                                         Index Cond: (series_id = potentially_drop_series.series_id)
                                                         Filter: (_ts_meta_max_1 >= '2021-02-11 13:11:07.779863+00'::timestamp with time zone)
                                             ->  Custom Scan (DecompressChunk) on _hyper_318_4497_chunk data_exists_2  (cost=2.51..2.51 rows=1000 width=8)
                                                   Filter: ("time" >= '2021-02-11 13:11:07.779863+00'::timestamp with time zone)
                                                   ->  Index Scan using compress_hyper_333_14717_chunk__compressed_hypertable_333_serie on compress_hyper_333_14717_chunk  (cost=0.29..2.51 rows=1 width=56)
                                                         Index Cond: (series_id = potentially_drop_series.series_id)
                                                         Filter: (_ts_meta_max_1 >= '2021-02-11 13:11:07.779863+00'::timestamp with time zone)
....
```

We also include a small optimization to not execute the label delete if
the array of labels is empty.

I think this will speed up the maintenance tasks quite a bit and thus
Fixes quite a few issues.

Fixes #663, #506, #596

### CODE REVIEW

**Review by jgpruitt — APPROVED** [review]
I don't yet fully understand 100% of all that's happening here, but the changes to the SQL make sense old vs. new

**Review by antekresic — APPROVED** [review]
Looks good! :+1:

**Review by Harkishen-Singh — APPROVED** [review]

**Comment by VineethReddy02** [comment]
LGTM!

**Pull request merged**
