### PR TITLE
Remove helm maintenance configuration

### PR DESCRIPTION
**Pull request by JamesGuthrie**

### CODE REVIEW

**Review by paulfantom — CHANGES_REQUESTED** [review]
overall lgtm, but we need to put a note somewhere that timescaledb 1.x is not supported anymore and that we recommend using promscale helm chart in version 0.6.0 if such support is needed.

**Comment by JamesGuthrie** [comment]
I agree. I had thought of adding that to the release notes, but I guess it might also help to have it in the helm-chart readme. I guess it depends on how likely we think it is that people will want to use promscale with timescale 1.x.

**Comment by paulfantom** [comment]
I think we should add it in both places - release notes and readme.

**Comment by JamesGuthrie** [comment]
done

**Review by paulfantom — APPROVED** [review]
lgtm

**Review by cevian — APPROVED** [review]

**Pull request merged**
