### PR TITLE
docs/mixin: add basic promscale dashboard

### PR DESCRIPTION
**Pull request by paulfantom**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue._

As in title

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

### CODE REVIEW

**Comment by paulfantom** [comment]
Few screenshots of the dashboard to simplify code review.

Dashboards are created with RED methodology in mind and with ideas from "Information Dashboard Design" by Stephen Few.

Default view:
Screenshot from 2022-03-15 10-56-56

Ingest section expanded:
Screenshot from 2022-03-15 10-57-12

Query section expanded:
Screenshot from 2022-03-15 10-57-20

Database section expanded:
Screenshot from 2022-03-15 10-57-28

Cache section expanded:
Screenshot from 2022-03-15 10-59-07

**Review by Harkishen-Singh — APPROVED** [review]
This is good but why don't I see mixin test CI in the list of CIs?

**Comment by paulfantom** [comment]
@Harkishen-Singh It is available under name "mixin / Check monitoring mixin" with link to details at https://github.com/timescale/promscale/runs/5551582575?check_suite_focus=true

**Comment by ramonguiu** [comment]
This is amazing @paulfantom ! Thanks so much. This will be so helpful to our users to troubleshoot their Promscale instances.

I have some questions / feedback:

1. In the overview users would like to get high level stats like samples / second, spans / second, total cardinality. amount of storage consumed for metrics and for traces and their compression rate. Is writes per second measuring individual samples / spans / other stuff per second or individual requests that could contain a number of those?
2.  Are we able to add the PG, TSDB, Toolkit and Promscale extension versions to the dashboard as well? (we can save this for a future version).
3. The reason the number of HTTP and gRPC requests is low is because of each request containing a batch of metrics / traces?
4. How should someone reason about ingest HTTP vs gRPC requests? Are gRPC requests also counted as part of HTTP requests? Can we differentiate by the different endpoints? How would someone know if most of them are Prometheus gRPC or OpenTelemetry gRPC?
5. For Query, what is this actually measuring? Which endpoints are included and could we break those down in the charts?
6. What does last maintenance job status OK mean? That it completed, that is ongoing as expected? Could we show how long those maintenance jobs are taking? 
7. Why does the cache latency (metrics) chart has gaps in some of the lines?
8. Is occupancy showing for each of the caches how close you're getting to the limit?

**Review by ramonguiu — COMMENTED** [review]
Added comments separately

**Comment by paulfantom** [comment]
Just to not that a primary function of this dashboard is to help in debugging and diagnosis after alerts fired. As such it doesn't contain panels that are meaningless from runbooks/alerts perspective. In essence, if we don't have an alert for that, there is no panel for it.

> In the overview users would like to get high level stats like samples / second, spans / second, total cardinality. amount of storage consumed for metrics and for traces and their compression rate. Is writes per second measuring individual samples / spans / other stuff per second or individual requests that could contain a number of those?

It is showing all ingest data types in per second manner (spans per second, samples per second, metadata per second, etc.). I put it on a graph panel to have a visibility over time and not just last value.

> total cardinality.

We don't have a metric for that, hence it is not included. 

> amount of storage consumed for metrics and for traces and their compression rate

We don't have metrics for that. Additionally amount of storage is not reported and probably shouldn't be reported by promscale. Compression rate is not reported and probably won't be due to performance issues when gathering this information. It is also useless from alerting pov.

> Are we able to add the PG, TSDB, Toolkit and Promscale extension versions to the dashboard as well? (we can save this for a future version).

Right now, we are not able to do this.

> The reason the number of HTTP and gRPC requests is low is because of each request containing a batch of metrics / traces?

The reason is that my instance is not doing anything :D 

> How should someone reason about ingest HTTP vs gRPC requests? Are gRPC requests also counted as part of HTTP requests? Can we differentiate by the different endpoints? How would someone know if most of them are Prometheus gRPC or OpenTelemetry gRPC?

In general gRPC is for otel, http is for prometheus. The differentiation is done commonly by protocol and not by endpoints due to how infrastructure can differ for different protocols. Basically what I am saying is that folks can have loadbalancers in front of promscale and for those it is more important to know protocol than what type of data is sent over this protocol (prometheus data, or traces, or others).

> For Query, what is this actually measuring? Which endpoints are included and could we break those down in the charts?

HTTP queries received by promscale. AFAIK currently there is only one endpoint for this.

> What does last maintenance job status OK mean? That it completed, that is ongoing as expected?

It means that the job was completed successfully. We cannot visualize how long job took to run due to possible performance issues in gathering that data and metric cardinality in prometheus.

> Could we show how long those maintenance jobs are taking?

This is covered by alerting.

> Why does the cache latency (metrics) chart has gaps in some of the lines?

It's a bug in how we report cache data and has nothing to do with the dashboard itself. (cc @Harkishen-Singh).

> Is occupancy showing for each of the caches how close you're getting to the limit?

Yes.

**Comment by ramonguiu** [comment]
> @ramonguiu Just to note that a primary function of this dashboard is to help in debugging and diagnosis after alerts fired. As such it doesn't contain panels that are meaningless from runbooks/alerts perspective. In essence, if we don't have an alert for that, there is no panel for it.

Ah ok, so this is just to have a dashboard you can link from the alerts / runbooks?

A lot of the information here with some extra things would be useful to provide a general overview of how Promscale is doing but it looks like you think there should be a separate dashboard for that? We can discuss in a future team meeting.

**Pull request merged**
