### PR TITLE
helm chart - typo in cronjob template

### PR DESCRIPTION
**Pull request by wileyj**
change `promscal` -> `promscale` on line 60

```
Error: UPGRADE FAILED: template: promscale/templates/cronjob-maintenance.yaml:60:25: executing "promscale/templates/cronjob-maintenance.yaml" at <include "promscal.fullname" .>: error calling include: template: no template "promscal.fullname" associated with template "gotpl"
```

### CODE REVIEW

**Comment by VineethReddy02** [comment]
Thanks for the fix @wileyj 

But the maintenance job is by default disabled from two releases as TimescaleDB does by using UDJ (user-defined jobs), Any specific reason why are you explicitly enabling the maintenance job?

**Comment by wileyj** [comment]
> Thanks for the fix @wileyj
> 
> But the maintenance job is by default disabled from two releases as TimescaleDB does by using UDJ (user-defined jobs), Any specific reason why are you explicitly enabling the maintenance job?

Yes - using timescale-cloud, there is apparently a bug in the postgres extension `2.4.1` and the suggestion from support was to enable the maintenance jobs in the meantime. 

Changing `false` to `true` (i did notice the comment about it not being needed https://github.com/timescale/promscale/blob/master/helm-chart/values.yaml#L96-L98) produced the error above.

**Comment by wileyj** [comment]
Plus, it never hurts to fix a typo! This one just happened to help me get past some storage usage issues using timescale-cloud.

**Review by cevian — APPROVED** [review]

**Comment by cevian** [comment]
@wileyj Thank you!

**Pull request merged**
