### PR TITLE
Bump prometheus and thanos versions

### PR DESCRIPTION
**Pull request by paulfantom**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue._

This is bumping thanos version to 0.24.0 (closing #1038) and also bumps prometheus to 2.31 (I couldn't make 2.32 work :shrug: ). The change is also modifying imports of prometheus packages due to changes in repository layout (https://github.com/prometheus/prometheus/pull/9478).

Purely internal change with nothing to communicate in changelog.

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

### CODE REVIEW

**Comment by cevian** [comment]
Lots of CI errors, will review once resolved

**Comment by paulfantom** [comment]
I missed that upstream prometheus wrapped `unit64` type as `storage.SeriesRef` and this affected some of our code, hence CI issues. This is fixed now and PR is ready for review.

**Review by JamesGuthrie — APPROVED** [review]
LGTM

**Review by cevian — APPROVED** [review]
LGTM

**Review by antekresic — APPROVED** [review]

**Review by Harkishen-Singh — APPROVED** [review]

**Pull request merged**
